CREATE DATABASE Account
GO
USE Account
GO

CREATE TABLE Account (
Matricola INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
Username VARCHAR(100) NOT NULL,
Password VARCHAR(100) NOT NULL,
SubscriptionDate DATE
)
